{% set name = "bar_chart_race" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 4c5554d0991548e43ce9226a28b8dae5a7f7a9955f5523ba36364d61d4701b1b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy >=1.15.0
    - matplotlib-base >=3.1.0
    - pandas >=0.24.0

test:
  imports:
    - bar_chart_race

about:
  home: https://dexplo.org/bar_chart_race
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Create animated bar chart races using matplotlib"
  doc_url: https://dexplo.org/bar_chart_race
  dev_url: https://github.com/dexplo/bar_chart_race

extra:
  recipe-maintainers:
    - tdpetrou
